language: node_js
node_js:
  - '0.8'
  - '0.10'
  - '0.11'
before_script:
  - npm install
script:
  - npm test
  - node_modules/.bin/grunt
env:
  global:
    - secure: eQZof8/hMB/0HFtSxsPdmE3ISErYXF2yrXzjuWEQTZ1qO69vrIoKsBaNZfB6UxfXt8MzfbZAqQWW55jqA7g9UFJ+vukwH0ohuYnt5rOg6o1OBp2j+pfzZ3EXDmtM3PXB3R1Y0HxGDIieIBd85AOfQ0zMcRoik8A5wz5/frSXN6Q=
    - secure: aVD0JtorIGR2qcizgRwMs9o3dowTf1GGFgRthbyY8uzTEdmuIjShxIqUkD1PBsai0kWH5rfdE8zI/ok3t6d0FOuUl4x5fh7sdr64q3LKK/eUdt5MFlhmSB2qbl9Yn1PniXGg2A7DaUuAOus79IuYYP6y3nsayvHAWw0MbCtkHKE=
